const FLAG_CODES = {
  MEX: 'mx', RSA: 'za', KOR: 'kr', CZE: 'cz',
  CAN: 'ca', BIH: 'ba', QAT: 'qa', SUI: 'ch',
  BRA: 'br', MAR: 'ma', HAI: 'ht', SCO: 'gb-sct',
  USA: 'us', PAR: 'py', AUS: 'au', TUR: 'tr',
  GER: 'de', CUW: 'cw', CIV: 'ci', ECU: 'ec',
  NED: 'nl', JPN: 'jp', SWE: 'se', TUN: 'tn',
  BEL: 'be', EGY: 'eg', IRN: 'ir', NZL: 'nz',
  ESP: 'es', CPV: 'cv', KSA: 'sa', URU: 'uy',
  FRA: 'fr', SEN: 'sn', IRQ: 'iq', NOR: 'no',
  ARG: 'ar', ALG: 'dz', AUT: 'at', JOR: 'jo',
  POR: 'pt', COD: 'cd', UZB: 'uz', COL: 'co',
  ENG: 'gb-eng', CRO: 'hr', GHA: 'gh', PAN: 'pa',
};

function getFlagUrl(teamId) {
  const code = FLAG_CODES[teamId];
  if (!code) return '';
  return `https://flagcdn.com/${code}.svg`;
}

const ALBUM_DATA = [
  /* ── FIGURINHAS GERAIS (FWC) ─────────────────────────────── */
  {
    group: 'FWC',
    label: 'Figurinhas Gerais',
    special: true,
    teams: [
      {
        id: 'FWC', name: 'Copa do Mundo 2026', flag: '🏆',
        players: [
          { num:  1, name: 'FWC 1'  },
          { num:  2, name: 'FWC 2'  },
          { num:  3, name: 'FWC 3'  },
          { num:  4, name: 'FWC 4'  },
          { num:  5, name: 'FWC 5'  },
          { num:  6, name: 'FWC 6'  },
          { num:  7, name: 'FWC 7'  },
          { num:  8, name: 'FWC 8'  },
          { num:  9, name: 'FWC 9'  },
          { num: 10, name: 'FWC 10' },
          { num: 11, name: 'FWC 11' },
          { num: 12, name: 'FWC 12' },
          { num: 14, name: 'FWC 14' },
          { num: 15, name: 'FWC 15' },
          { num: 16, name: 'FWC 16' },
          { num: 17, name: 'FWC 17' },
          { num: 18, name: 'FWC 18' },
          { num: 19, name: 'FWC 19' },
        ]
      }
    ]
  },

  /* ── GRUPO A ──────────────────────────────────────────────── */
  {
    group: 'A', label: 'Grupo A',
    teams: [
      {
        id: 'MEX', name: 'México', flag: '🇲🇽',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Luis Malagón' },
          { num:  3, name: 'Joan Vásquez' },
          { num:  4, name: 'Jorge Sánchez' },
          { num:  5, name: 'César Montes' },
          { num:  6, name: 'Jesús Gallardo' },
          { num:  7, name: 'Israel Reyes' },
          { num:  8, name: 'Diego Lainez' },
          { num:  9, name: 'Carlos Rodríguez' },
          { num: 10, name: 'Edson Álvarez' },
          { num: 11, name: 'Orbelín Pineda' },
          { num: 12, name: 'Marcel Ruiz' },
          { num: 14, name: 'Erick Sánchez' },
          { num: 15, name: 'Hirving Lozano' },
          { num: 16, name: 'Santiago Giménez' },
          { num: 17, name: 'Raúl Jiménez' },
          { num: 18, name: 'Alexis Vega' },
          { num: 19, name: 'Roberto Alvarado' },
          { num: 20, name: 'César Huerta' },
        ]
      },
      {
        id: 'RSA', name: 'África do Sul', flag: '🇿🇦',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Ronwen Williams' },
          { num:  3, name: 'Sifiso Chune' },
          { num:  4, name: 'Aubrey Modiba' },
          { num:  5, name: 'Samukele Kabini' },
          { num:  6, name: 'Mbekezeli Mbokazi' },
          { num:  7, name: 'Khulekani Ndamane' },
          { num:  8, name: 'Siyabonga Ngezana' },
          { num:  9, name: 'Khuliso Mudau' },
          { num: 10, name: 'Nkosinathi Sibisi' },
          { num: 11, name: 'Teboho Mokoena' },
          { num: 12, name: 'Thalente Mbatha' },
          { num: 14, name: 'Bathusi Aubaas' },
          { num: 15, name: 'Vina Sithole' },
          { num: 16, name: 'Sipho Mbule' },
          { num: 17, name: 'Lyle Foster' },
          { num: 18, name: 'Ndlamu Ravners' },
          { num: 19, name: 'Mohau Nkota' },
          { num: 20, name: 'Oswin Appollis' },
        ]
      },
      {
        id: 'KOR', name: 'Coreia do Sul', flag: '🇰🇷',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Hyeonwoo Jo' },
          { num:  3, name: 'Seungwu Kim' },
          { num:  4, name: 'Minjae Kim' },
          { num:  5, name: 'Yumin Cho' },
          { num:  6, name: 'Youngwoo Seol' },
          { num:  7, name: 'Hanbeom Lee' },
          { num:  8, name: 'Taeseok Lee' },
          { num:  9, name: 'Myungjae Lee' },
          { num: 10, name: 'Jaesung Lee' },
          { num: 11, name: 'Inbeom Hwang' },
          { num: 12, name: 'Kangin Lee' },
          { num: 14, name: 'Seungho Paik' },
          { num: 15, name: 'Jens Castrop' },
          { num: 16, name: 'Donggyeong Lee' },
          { num: 17, name: 'Guesung Cho' },
          { num: 18, name: 'Heungmin Son' },
          { num: 19, name: 'Heechan Hwang' },
          { num: 20, name: 'Yugyeong Oh' },
        ]
      },
      {
        id: 'CZE', name: 'República Tcheca', flag: '🇨🇿',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Matej Kovár' },
          { num:  3, name: 'Jaroslav Stanek' },
          { num:  4, name: 'Ladislav Krejcí' },
          { num:  5, name: 'Vladimír Coufal' },
          { num:  6, name: 'Jaroslav Zeleny' },
          { num:  7, name: 'Tomás Holes' },
          { num:  8, name: 'David Zima' },
          { num:  9, name: 'Michal Sadílek' },
          { num: 10, name: 'Lukás Provod' },
          { num: 11, name: 'Lukás Cerv' },
          { num: 12, name: 'Tomás Soucek' },
          { num: 14, name: 'Pavel Sulc' },
          { num: 15, name: 'Matej Vydra' },
          { num: 16, name: 'Vasil Kusej' },
          { num: 17, name: 'Tomás Chorv' },
          { num: 18, name: 'Václav Cerný' },
          { num: 19, name: 'Adam Hlozek' },
          { num: 20, name: 'Patrik Schick' },
        ]
      },
    ]
  },

  /* ── GRUPO B ──────────────────────────────────────────────── */
  {
    group: 'B', label: 'Grupo B',
    teams: [
      {
        id: 'CAN', name: 'Canadá', flag: '🇨🇦',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Dayne St. Clair' },
          { num:  3, name: 'Alphonso Davies' },
          { num:  4, name: 'Alistair Johnston' },
          { num:  5, name: 'Samuel Adekugbe' },
          { num:  6, name: 'Richie Laryea' },
          { num:  7, name: 'Derek Cornelius' },
          { num:  8, name: 'Moïse Bombito' },
          { num:  9, name: 'Kamal Miller' },
          { num: 10, name: 'Stephen Eustaquio' },
          { num: 11, name: 'Ismaël Koné' },
          { num: 12, name: 'Jonathan Osorio' },
          { num: 14, name: 'Jacob Shaffelburg' },
          { num: 15, name: 'Mathieu Choinière' },
          { num: 16, name: 'Niko Sigur' },
          { num: 17, name: 'Tajon Buchanan' },
          { num: 18, name: 'Liam Millar' },
          { num: 19, name: 'Cyle Larin' },
          { num: 20, name: 'Jonathan David' },
        ]
      },
      {
        id: 'BIH', name: 'Bósnia-Herzegovina', flag: '🇧🇦',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Nikola Vasilj' },
          { num:  3, name: 'Amar Dedic' },
          { num:  4, name: 'Sead Kolasinac' },
          { num:  5, name: 'Tarik Muharemovic' },
          { num:  6, name: 'Nihad Mujakic' },
          { num:  7, name: 'Nikola Katic' },
          { num:  8, name: 'Amir Hadziahmetovic' },
          { num:  9, name: 'Benjamin Tahirovic' },
          { num: 10, name: 'Armin Gigovic' },
          { num: 11, name: 'Ivan Sunje' },
          { num: 12, name: 'Ivan Basic' },
          { num: 14, name: 'Dzenis Burnig' },
          { num: 15, name: 'Esmir Bajraktarevic' },
          { num: 16, name: 'Amar Memic' },
          { num: 17, name: 'Ermedin Demirovic' },
          { num: 18, name: 'Edin Dzeko' },
          { num: 19, name: 'Samed Bazdar' },
          { num: 20, name: 'Haris Tabakovic' },
        ]
      },
      {
        id: 'QAT', name: 'Catar', flag: '🇶🇦',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Meshaal Barsham' },
          { num:  3, name: 'Sultan Albrake' },
          { num:  4, name: 'Lucas Mendes' },
          { num:  5, name: 'Homam Ahmed' },
          { num:  6, name: 'Boualem Khoukhi' },
          { num:  7, name: 'Pedro Miguel' },
          { num:  8, name: 'Tarek Salman' },
          { num:  9, name: 'Mohammed Mannai' },
          { num: 10, name: 'Karim Boudiaf' },
          { num: 11, name: 'Assim Madibo' },
          { num: 12, name: 'Hamed Fateh' },
          { num: 14, name: 'Mohammed Waad' },
          { num: 15, name: 'Abdulaziz Hatem' },
          { num: 16, name: 'Hassan Al-Haydos' },
          { num: 17, name: 'Edmilson Junior' },
          { num: 18, name: 'Akram Hassan Afif' },
          { num: 19, name: 'Ahmed Al-Ganehi' },
          { num: 20, name: 'Almoez Ali' },
        ]
      },
      {
        id: 'SUI', name: 'Suíça', flag: '🇨🇭',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Gregor Kobel' },
          { num:  3, name: 'Von Moos' },
          { num:  4, name: 'Manuel Akanji' },
          { num:  5, name: 'Ricardo Rodríguez' },
          { num:  6, name: 'Nico Elvedi' },
          { num:  7, name: 'Aurèle Amenda' },
          { num:  8, name: 'Silvan Widmer' },
          { num:  9, name: 'Granit Xhaka' },
          { num: 10, name: 'Denis Zakaria' },
          { num: 11, name: 'Remo Freuler' },
          { num: 12, name: 'Fabian Rieder' },
          { num: 14, name: 'Ardon Jashari' },
          { num: 15, name: 'Joëlann Manzambi' },
          { num: 16, name: 'Michel Aebischer' },
          { num: 17, name: 'Breel Embolo' },
          { num: 18, name: 'Ruben Vargas' },
          { num: 19, name: 'Dan Ndoye' },
          { num: 20, name: 'Zeki Amdouni' },
        ]
      },
    ]
  },

  /* ── GRUPO C ──────────────────────────────────────────────── */
  {
    group: 'C', label: 'Grupo C',
    teams: [
      {
        id: 'BRA', name: 'Brasil', flag: '🇧🇷',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Alisson' },
          { num:  3, name: 'Bento' },
          { num:  4, name: 'Marquinhos' },
          { num:  5, name: 'Éder Militão' },
          { num:  6, name: 'Gabriel Magalhães' },
          { num:  7, name: 'Danilo' },
          { num:  8, name: 'Wesley' },
          { num:  9, name: 'Lucas Paquetá' },
          { num: 10, name: 'Casemiro' },
          { num: 11, name: 'Bruno Guimarães' },
          { num: 12, name: 'Luiz Henrique' },
          { num: 14, name: 'Vinícius Júnior' },
          { num: 15, name: 'Rodrygo' },
          { num: 16, name: 'João Pedro' },
          { num: 17, name: 'Matheus Cunha' },
          { num: 18, name: 'Gabriel Martinelli' },
          { num: 19, name: 'Raphinha' },
          { num: 20, name: 'Estêvão' },
        ]
      },
      {
        id: 'MAR', name: 'Marrocos', flag: '🇲🇦',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Yassine Bounou' },
          { num:  3, name: 'Munir El Kajoui' },
          { num:  4, name: 'Achraf Hakimi' },
          { num:  5, name: 'Nousair Mazraoui' },
          { num:  6, name: 'Nayef Aguerd' },
          { num:  7, name: 'Romain Saïss' },
          { num:  8, name: 'Jawad El Yamiq' },
          { num:  9, name: 'Adam Masina' },
          { num: 10, name: 'Sofyan Amrabat' },
          { num: 11, name: 'Azzedine Ounahi' },
          { num: 12, name: 'Ilias Ben Seghir' },
          { num: 14, name: 'Bilal El Khannouss' },
          { num: 15, name: 'Ismail Saibari' },
          { num: 16, name: 'Youssef En-Nesyri' },
          { num: 17, name: 'Azziz Ezzalzouli' },
          { num: 18, name: 'Soufiane Rahimi' },
          { num: 19, name: 'Brahim Díaz' },
          { num: 20, name: 'Ayoub El Kaabi' },
        ]
      },
      {
        id: 'HAI', name: 'Haiti', flag: '🇭🇹',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Johny Placide' },
          { num:  3, name: 'Carlens Arcus' },
          { num:  4, name: 'Martin Experience' },
          { num:  5, name: 'Jean-Kevin Duverne' },
          { num:  6, name: 'Ricardo Ade' },
          { num:  7, name: 'Duke Lacroix' },
          { num:  8, name: 'Garven Metusala' },
          { num:  9, name: 'Hannes Delcroix' },
          { num: 10, name: 'Leverton Pierre' },
          { num: 11, name: 'Danley Jean Jacques' },
          { num: 12, name: 'Jean-Michel Bellegarde' },
          { num: 14, name: 'Christopher Attys' },
          { num: 15, name: 'Derrick Etienne Jr.' },
          { num: 16, name: 'Josué Casimir' },
          { num: 17, name: 'Ruben Providence' },
          { num: 18, name: 'Duckens Nazon' },
          { num: 19, name: 'Loucius Dedson' },
          { num: 20, name: 'Frantziou Pierrot' },
        ]
      },
      {
        id: 'SCO', name: 'Escócia', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Angus Gunn' },
          { num:  3, name: 'Jack Hendry' },
          { num:  4, name: 'Kieran Tierney' },
          { num:  5, name: 'Aaron Hickey' },
          { num:  6, name: 'Andrew Robertson' },
          { num:  7, name: 'Scott McKenna' },
          { num:  8, name: 'John Souttar' },
          { num:  9, name: 'Anthony Ralston' },
          { num: 10, name: 'Grant Hanley' },
          { num: 11, name: 'Scott McTominay' },
          { num: 12, name: 'Billy Gilmour' },
          { num: 14, name: 'Lewis Ferguson' },
          { num: 15, name: 'Ryan Christie' },
          { num: 16, name: 'Kenny McLean' },
          { num: 17, name: 'John McGinn' },
          { num: 18, name: 'Lyndon Dykes' },
          { num: 19, name: 'Che Adams' },
          { num: 20, name: 'Ben Doak' },
        ]
      },
    ]
  },

  /* ── GRUPO D ──────────────────────────────────────────────── */
  {
    group: 'D', label: 'Grupo D',
    teams: [
      {
        id: 'USA', name: 'Estados Unidos', flag: '🇺🇸',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Matt Freese' },
          { num:  3, name: 'Chris Richards' },
          { num:  4, name: 'Tim Ream' },
          { num:  5, name: 'Mark McKenzie' },
          { num:  6, name: 'Alex Freeman' },
          { num:  7, name: 'Antonee Robinson' },
          { num:  8, name: 'Tyler Adams' },
          { num:  9, name: 'Tanner Tessmann' },
          { num: 10, name: 'Weston McKennie' },
          { num: 11, name: 'Cristian Roldan' },
          { num: 12, name: 'Timothy Weah' },
          { num: 14, name: 'Diego Luna' },
          { num: 15, name: 'Malik Tillman' },
          { num: 16, name: 'Christian Pulisic' },
          { num: 17, name: 'Brenden Aaronson' },
          { num: 18, name: 'Ricardo Pepi' },
          { num: 19, name: 'Haji Wright' },
          { num: 20, name: 'Folarin Balogun' },
        ]
      },
      {
        id: 'PAR', name: 'Paraguai', flag: '🇵🇾',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Roberto Fernández' },
          { num:  3, name: 'Orlando Gill' },
          { num:  4, name: 'Gustavo Gómez' },
          { num:  5, name: 'Fabián Balbuena' },
          { num:  6, name: 'Juan José Cáceres' },
          { num:  7, name: 'Omar Alderete' },
          { num:  8, name: 'Junior Alonso' },
          { num:  9, name: 'Mathías Villasanti' },
          { num: 10, name: 'Diego Gómez' },
          { num: 11, name: 'Damián Bobadilla' },
          { num: 12, name: 'Andrés Cubas' },
          { num: 14, name: 'Matías Galarza' },
          { num: 15, name: 'Julio Enciso' },
          { num: 16, name: 'Alejandro Romero Gamarra' },
          { num: 17, name: 'Miguel Almirón' },
          { num: 18, name: 'Ramón Sosa' },
          { num: 19, name: 'Ángel Romero' },
          { num: 20, name: 'Antonio Sanabria' },
        ]
      },
      {
        id: 'AUS', name: 'Austrália', flag: '🇦🇺',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Mathew Ryan' },
          { num:  3, name: 'Joe Gauci' },
          { num:  4, name: 'Harry Souttar' },
          { num:  5, name: 'Alessandro Circati' },
          { num:  6, name: 'Jordan Bos' },
          { num:  7, name: 'Aziz Behich' },
          { num:  8, name: 'Cameron Burgess' },
          { num:  9, name: 'Lewis Miller' },
          { num: 10, name: 'Milos Degenek' },
          { num: 11, name: 'Jackson Irvine' },
          { num: 12, name: 'Riley McGree' },
          { num: 14, name: "Aiden O'Neill" },
          { num: 15, name: 'Connor Metcalfe' },
          { num: 16, name: 'Patrick Yazbek' },
          { num: 17, name: 'Craig Goodwin' },
          { num: 18, name: 'Kusini Yengi' },
          { num: 19, name: 'Nestory Irankunda' },
          { num: 20, name: 'Mohamed Toure' },
        ]
      },
      {
        id: 'TUR', name: 'Turquia', flag: '🇹🇷',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Uğurcan Çakır' },
          { num:  3, name: 'Mert Müldür' },
          { num:  4, name: 'Zeki Çelik' },
          { num:  5, name: 'Abdülkerim Bardakcı' },
          { num:  6, name: 'Çağlar Söyüncü' },
          { num:  7, name: 'Merih Demiral' },
          { num:  8, name: 'Ferdi Kadıoğlu' },
          { num:  9, name: 'Kaan Ayhan' },
          { num: 10, name: 'İsmail Yüksek' },
          { num: 11, name: 'Hakan Çalhanoğlu' },
          { num: 12, name: 'Orkun Kökçü' },
          { num: 14, name: 'Arda Güler' },
          { num: 15, name: 'İrfan Can Kahveci' },
          { num: 16, name: 'Yunus Akgün' },
          { num: 17, name: 'İsan Uzun' },
          { num: 18, name: 'Alper Yılmaz' },
          { num: 19, name: 'Kerem Aktürkoğlu' },
          { num: 20, name: 'Kenan Yıldız' },
        ]
      },
    ]
  },

  /* ── GRUPO E ──────────────────────────────────────────────── */
  {
    group: 'E', label: 'Grupo E',
    teams: [
      {
        id: 'GER', name: 'Alemanha', flag: '🇩🇪',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Marc-André ter Stegen' },
          { num:  3, name: 'Jonathan Tah' },
          { num:  4, name: 'David Raum' },
          { num:  5, name: 'Nico Schlotterbeck' },
          { num:  6, name: 'Antonio Rüdiger' },
          { num:  7, name: 'Maximilian Mittelstädt' },
          { num:  8, name: 'Rolf Baku' },
          { num:  9, name: 'Thomas Müller' },
          { num: 10, name: 'Joshua Kimmich' },
          { num: 11, name: 'Florian Wirtz' },
          { num: 12, name: 'Felix Nmecha' },
          { num: 14, name: 'Leon Goretzka' },
          { num: 15, name: 'Jamal Musiala' },
          { num: 16, name: 'Serge Gnabry' },
          { num: 17, name: 'Kai Havertz' },
          { num: 18, name: 'Leroy Sané' },
          { num: 19, name: 'Karim Adeyemi' },
          { num: 20, name: 'Nick Woltemade' },
        ]
      },
      {
        id: 'CUW', name: 'Curaçao', flag: '🇨🇼',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Eloy Room' },
          { num:  3, name: 'Armando Obispo' },
          { num:  4, name: 'Sherel Floranus' },
          { num:  5, name: 'Jurien Gaari' },
          { num:  6, name: 'Joshua Brenet' },
          { num:  7, name: 'Roohon van Elima' },
          { num:  8, name: 'Briandy Samboe' },
          { num:  9, name: 'Lirano Comencencia' },
          { num: 10, name: 'Godfried Roemeratoe' },
          { num: 11, name: 'Juninho Bacuna' },
          { num: 12, name: 'Leandro Bacuna' },
          { num: 14, name: 'Tayiti Chong' },
          { num: 15, name: 'Kengu Gorre' },
          { num: 16, name: 'Jean Margaritha' },
          { num: 17, name: 'Jørgen Locadia' },
          { num: 18, name: 'Jeremy Antonisse' },
          { num: 19, name: 'Gernane Kastaneer' },
          { num: 20, name: 'Sonkie Hansen' },
        ]
      },
      {
        id: 'CIV', name: "Costa do Marfim", flag: '🇨🇮',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Yoann Fofana' },
          { num:  3, name: 'Odirsane Koman' },
          { num:  4, name: 'Wilfried Singo' },
          { num:  5, name: 'Odilon Kossounou' },
          { num:  6, name: 'Evan Ndicka' },
          { num:  7, name: 'Willy Boly' },
          { num:  8, name: 'Emmanuel Agbadou' },
          { num:  9, name: 'Dusiane Diomandé' },
          { num: 10, name: 'Franck Kessié' },
          { num: 11, name: 'Seko Fofana' },
          { num: 12, name: 'Ibrahima Sangaré' },
          { num: 14, name: 'Jean-Philippe Gbamin' },
          { num: 15, name: 'Amad Diallo' },
          { num: 16, name: 'Sébastian Haller' },
          { num: 17, name: 'Adm/Mina' },
          { num: 18, name: 'Yoro Diomandé' },
          { num: 19, name: 'Liman Guessand' },
          { num: 20, name: 'Daman Diantte' },
        ]
      },
      {
        id: 'ECU', name: 'Equador', flag: '🇪🇨',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Hernán Galíndez' },
          { num:  3, name: 'Berman Valle' },
          { num:  4, name: 'Piero Hincapié' },
          { num:  5, name: 'Pervis Estupiñán' },
          { num:  6, name: 'William Pacho' },
          { num:  7, name: 'Ángelo Preciado' },
          { num:  8, name: 'Joel Gruezo' },
          { num:  9, name: 'Moisés Caicedo' },
          { num: 10, name: 'Alan Franco' },
          { num: 11, name: 'Kendry Páez' },
          { num: 12, name: 'Pedro Vite' },
          { num: 14, name: 'John Yeboah' },
          { num: 15, name: 'Leonardo Campana' },
          { num: 16, name: 'Gonzalo Plata' },
          { num: 17, name: 'Nelson Angulo' },
          { num: 18, name: 'Alan Minda' },
          { num: 19, name: 'Kevin Rodríguez' },
          { num: 20, name: 'Enner Valencia' },
        ]
      },
    ]
  },

  /* ── GRUPO F ──────────────────────────────────────────────── */
  {
    group: 'F', label: 'Grupo F',
    teams: [
      {
        id: 'NED', name: 'Países Baixos', flag: '🇳🇱',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Bart Verbruggen' },
          { num:  3, name: 'Virgil van Dijk' },
          { num:  4, name: 'Nicky van de Ven' },
          { num:  5, name: 'Jurriën Timber' },
          { num:  6, name: 'Denzel Dumfries' },
          { num:  7, name: 'Nathan Aké' },
          { num:  8, name: 'Jeremie Frimpong' },
          { num:  9, name: 'Jan Paul van Hecke' },
          { num: 10, name: 'Tijjani Reijnders' },
          { num: 11, name: 'Ryan Gravenberch' },
          { num: 12, name: 'Teun Koopmeiners' },
          { num: 14, name: 'Frenkie de Jong' },
          { num: 15, name: 'Xavi Simons' },
          { num: 16, name: 'Justin Kluivert' },
          { num: 17, name: 'Memphis Depay' },
          { num: 18, name: 'Donyell Malen' },
          { num: 19, name: 'Wout Weghorst' },
          { num: 20, name: 'Cody Gakpo' },
        ]
      },
      {
        id: 'JPN', name: 'Japão', flag: '🇯🇵',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Zion Suzuki' },
          { num:  3, name: 'Hidemasa Morishima' },
          { num:  4, name: 'Ryomei Seko' },
          { num:  5, name: 'Jjannosuke Suzuki' },
          { num:  6, name: 'Shogo Taniguchi' },
          { num:  7, name: 'Tsuna Watanabe' },
          { num:  8, name: 'Kanshi Sano' },
          { num:  9, name: 'Yuki Soma' },
          { num: 10, name: 'Ao Tanaka' },
          { num: 11, name: 'Daichi Kamada' },
          { num: 12, name: 'Takefusa Kubo' },
          { num: 14, name: 'Ritsu Doan' },
          { num: 15, name: 'Keito Nakamura' },
          { num: 16, name: 'Takumi Minamino' },
          { num: 17, name: 'Shuto Machino' },
          { num: 18, name: 'Jáwa Ito' },
          { num: 19, name: 'Koki Ogawa' },
          { num: 20, name: 'Naissa Ueda' },
        ]
      },
      {
        id: 'SWE', name: 'Suécia', flag: '🇸🇪',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Viktor Johansson' },
          { num:  3, name: 'Isak Hein' },
          { num:  4, name: 'Gabriel Gudmundsson' },
          { num:  5, name: 'Emil Holm' },
          { num:  6, name: 'Victor Nilsson Lindelöf' },
          { num:  7, name: 'Gustav Lagerbielke' },
          { num:  8, name: 'Lucas Bergvall' },
          { num:  9, name: 'Keo Larsson' },
          { num: 10, name: 'Jesper Karlström' },
          { num: 11, name: 'Vson Avari' },
          { num: 12, name: 'Mattias Svanberg' },
          { num: 14, name: 'Daniel Svensson' },
          { num: 15, name: 'Ken Sema' },
          { num: 16, name: 'Robin Barooh' },
          { num: 17, name: 'Kuuijsenso' },
          { num: 18, name: 'Anthony Elanga' },
          { num: 19, name: 'Alexander Isak' },
          { num: 20, name: 'Viktor Gyökeres' },
        ]
      },
      {
        id: 'TUN', name: 'Tunísia', flag: '🇹🇳',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Bechir Ben Said' },
          { num:  3, name: 'Jonca Dahmen' },
          { num:  4, name: 'Van Valery' },
          { num:  5, name: 'Montassar Talbi' },
          { num:  6, name: 'Yassine Meriah' },
          { num:  7, name: 'Ali Abdi' },
          { num:  8, name: 'Dylan Bronn' },
          { num:  9, name: 'Ellyes Skhiri' },
          { num: 10, name: 'Aïssa Laïdouni' },
          { num: 11, name: 'Ferjani Sassi' },
          { num: 12, name: 'Mohamed Ali Ben Romdhane' },
          { num: 14, name: 'Hannibal Mejbri' },
          { num: 15, name: 'Elias Achouri' },
          { num: 16, name: 'Elias Saad' },
          { num: 17, name: 'Hazem Mastouri' },
          { num: 18, name: 'Ismaël Gharbi' },
          { num: 19, name: 'Simyallah Ltaief' },
          { num: 20, name: 'Naïm Sliti' },
        ]
      },
    ]
  },

  /* ── GRUPO G ──────────────────────────────────────────────── */
  {
    group: 'G', label: 'Grupo G',
    teams: [
      {
        id: 'BEL', name: 'Bélgica', flag: '🇧🇪',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Thibaut Courtois' },
          { num:  3, name: 'Kétas Theate' },
          { num:  4, name: 'Timothy Castagne' },
          { num:  5, name: 'Zeno Debast' },
          { num:  6, name: 'Brandon Mechele' },
          { num:  7, name: 'Maxim De Cuyper' },
          { num:  8, name: 'Thomas Meunier' },
          { num:  9, name: 'Youri Tielemans' },
          { num: 10, name: 'Amadou Onana' },
          { num: 11, name: 'Nicolas Raskin' },
          { num: 12, name: 'Alexis Saelemaekers' },
          { num: 14, name: 'Hans Vanaken' },
          { num: 15, name: 'Kevin De Bruyne' },
          { num: 16, name: 'Jérémy Doku' },
          { num: 17, name: 'Charles De Ketelaere' },
          { num: 18, name: 'Leandro Trossard' },
          { num: 19, name: 'Loïs Openda' },
          { num: 20, name: 'Romelu Lukaku' },
        ]
      },
      {
        id: 'EGY', name: 'Egito', flag: '🇪🇬',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Mohamed Elshennawy' },
          { num:  3, name: 'Mohamed Hamdy' },
          { num:  4, name: 'Mohamed Hamdi' },
          { num:  5, name: 'Wasser Ibrahim' },
          { num:  6, name: 'Khaled Sobhi' },
          { num:  7, name: 'Ramy Rabia' },
          { num:  8, name: 'Kossam Abdelmaguid' },
          { num:  9, name: 'Ahmed Fatouh' },
          { num: 10, name: 'Marwan Attia' },
          { num: 11, name: 'Zizo' },
          { num: 12, name: 'Hamdy Fathy' },
          { num: 14, name: 'Mostafa Lasheen' },
          { num: 15, name: 'Emam Ashour' },
          { num: 16, name: 'Osama Faisal' },
          { num: 17, name: 'Mohamed Salah' },
          { num: 18, name: 'Mostafa Mohamed' },
          { num: 19, name: 'Trezeguet' },
          { num: 20, name: 'Omar Marmoush' },
        ]
      },
      {
        id: 'IRN', name: 'Irã', flag: '🇮🇷',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Alireza Beiranvand' },
          { num:  3, name: 'Morteza Pouraliganji' },
          { num:  4, name: 'Ehsan Hajsafi' },
          { num:  5, name: 'Milad Mohammadi' },
          { num:  6, name: 'Shojae Khalilzadeh' },
          { num:  7, name: 'Ramin Rezaeian' },
          { num:  8, name: 'Hossein Kanaani' },
          { num:  9, name: 'Sadegh Moharrami' },
          { num: 10, name: 'Saleh Hardani' },
          { num: 11, name: 'Saeid Ezatolahi' },
          { num: 12, name: 'Saman Ghoddos' },
          { num: 14, name: 'Omid Noorafkan' },
          { num: 15, name: 'Roozbeh Cheshmi' },
          { num: 16, name: 'Mohammad Mohebi' },
          { num: 17, name: 'Sardar Azmoun' },
          { num: 18, name: 'Mehdi Taremi' },
          { num: 19, name: 'Alireza Jahanbakhsh' },
          { num: 20, name: 'Ali Gholizadeh' },
        ]
      },
      {
        id: 'NZL', name: 'Nova Zelândia', flag: '🇳🇿',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Max Crocombe' },
          { num:  3, name: 'Alex Paulsen' },
          { num:  4, name: 'Michael Boxall' },
          { num:  5, name: 'Liberato Cacace' },
          { num:  6, name: 'Tim Payne' },
          { num:  7, name: 'Tyler Bindon' },
          { num:  8, name: 'Francis De Vries' },
          { num:  9, name: 'Finn Surman' },
          { num: 10, name: 'Joe Bell' },
          { num: 11, name: 'Sarpreet Singh' },
          { num: 12, name: 'Ryan Thomas' },
          { num: 14, name: 'Matthew Garbett' },
          { num: 15, name: 'Marko Stamenic' },
          { num: 16, name: 'Ben Old' },
          { num: 17, name: 'Chris Wood' },
          { num: 18, name: 'Elijah Just' },
          { num: 19, name: 'Callum McCowatt' },
          { num: 20, name: 'Kosta Barbarouses' },
        ]
      },
    ]
  },

  /* ── GRUPO H ──────────────────────────────────────────────── */
  {
    group: 'H', label: 'Grupo H',
    teams: [
      {
        id: 'ESP', name: 'Espanha', flag: '🇪🇸',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Unai Simón' },
          { num:  3, name: 'Robin Le Normand' },
          { num:  4, name: 'Aymeric Laporte' },
          { num:  5, name: 'Dean Huijsen' },
          { num:  6, name: 'Pedro Porro' },
          { num:  7, name: 'Dani Carvajal' },
          { num:  8, name: 'Marc Cucurella' },
          { num:  9, name: 'Martín Zubimendi' },
          { num: 10, name: 'Rodri' },
          { num: 11, name: 'Pedri' },
          { num: 12, name: 'Fabián Ruiz' },
          { num: 14, name: 'Mikel Merino' },
          { num: 15, name: 'Lamine Yamal' },
          { num: 16, name: 'Dani Olmo' },
          { num: 17, name: 'Nico Williams' },
          { num: 18, name: 'Ferran Torres' },
          { num: 19, name: 'Álvaro Morata' },
          { num: 20, name: 'Mikel Oyarzabal' },
        ]
      },
      {
        id: 'CPV', name: 'Cabo Verde', flag: '🇨🇻',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Vozinha' },
          { num:  3, name: 'Lucas Costa' },
          { num:  4, name: 'Pico' },
          { num:  5, name: 'Dinev' },
          { num:  6, name: 'Steven Moreira' },
          { num:  7, name: 'Wagner Pina' },
          { num:  8, name: 'João Paulo' },
          { num:  9, name: 'Jamick Semedo' },
          { num: 10, name: 'Kevin Pina' },
          { num: 11, name: 'Patrick Andrade' },
          { num: 12, name: 'Jamiro Monteiro' },
          { num: 14, name: 'Djeiny Duarte' },
          { num: 15, name: 'Garry Rodrigues' },
          { num: 16, name: 'Arnaut Cabral' },
          { num: 17, name: 'Ryan Mendes' },
          { num: 18, name: 'Dallon Livramento' },
          { num: 19, name: 'Willy Semedo' },
          { num: 20, name: 'Bebé' },
        ]
      },
      {
        id: 'KSA', name: 'Arábia Saudita', flag: '🇸🇦',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Nawaf Alaqidi' },
          { num:  3, name: 'Abdulrahman Alsamei' },
          { num:  4, name: 'Saud Abdulhamid' },
          { num:  5, name: 'Ninae Buwashl' },
          { num:  6, name: 'Jehad Thikri' },
          { num:  7, name: 'Motib Alharbi' },
          { num:  8, name: 'Hassan Altambakti' },
          { num:  9, name: 'Msabi Aljuwayin' },
          { num: 10, name: 'Zeyad Aljohani' },
          { num: 11, name: 'Abdullah Alkhaibari' },
          { num: 12, name: 'Nasser Aldawsari' },
          { num: 14, name: 'Saleh Abulshanannat' },
          { num: 15, name: 'Khogaman Alsahafi' },
          { num: 16, name: 'Salem Aldawsari' },
          { num: 17, name: 'Abdulelah Aldrud' },
          { num: 18, name: 'Feras Albrikan' },
          { num: 19, name: 'Saleh Alshehri' },
          { num: 20, name: 'Abdullah Alhamdah' },
        ]
      },
      {
        id: 'URU', name: 'Uruguai', flag: '🇺🇾',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Sergio Rochet' },
          { num:  3, name: 'Santiago Mele' },
          { num:  4, name: 'Ronald Araújo' },
          { num:  5, name: 'José María Giménez' },
          { num:  6, name: 'Sebastián Cáceres' },
          { num:  7, name: 'Mathías Olivera' },
          { num:  8, name: 'Guillermo Varela' },
          { num:  9, name: 'Martín Cáceres' },
          { num: 10, name: 'Federico Valverde' },
          { num: 11, name: 'Giorgian de Arrascaeta' },
          { num: 12, name: 'Rodrigo Bentancur' },
          { num: 14, name: 'Manuel Ugarte' },
          { num: 15, name: 'Nicolás de la Cruz' },
          { num: 16, name: 'Maxi Araújo' },
          { num: 17, name: 'Darwin Núñez' },
          { num: 18, name: 'Federico Viñas' },
          { num: 19, name: 'Rodrigo Aguirre' },
          { num: 20, name: 'Facundo Pellistri' },
        ]
      },
    ]
  },

  /* ── GRUPO I ──────────────────────────────────────────────── */
  {
    group: 'I', label: 'Grupo I',
    teams: [
      {
        id: 'FRA', name: 'França', flag: '🇫🇷',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Mike Maignan' },
          { num:  3, name: 'Théo Hernández' },
          { num:  4, name: 'William Saliba' },
          { num:  5, name: 'Jules Koundé' },
          { num:  6, name: 'Ibrahima Konaté' },
          { num:  7, name: 'Dayot Upamecano' },
          { num:  8, name: 'Lucas Digne' },
          { num:  9, name: 'Aurélien Tchouaméni' },
          { num: 10, name: 'Eduardo Camavinga' },
          { num: 11, name: 'Manu Koné' },
          { num: 12, name: 'Adrien Rabiot' },
          { num: 14, name: 'Michael Olise' },
          { num: 15, name: 'Ousmane Dembélé' },
          { num: 16, name: 'Bradley Barcola' },
          { num: 17, name: 'Désiré Doué' },
          { num: 18, name: 'Kingsley Coman' },
          { num: 19, name: 'Hugo Ekitiké' },
          { num: 20, name: 'Kylian Mbappé' },
        ]
      },
      {
        id: 'SEN', name: 'Senegal', flag: '🇸🇳',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Édouard Mendy' },
          { num:  3, name: 'Yehvann Diouf' },
          { num:  4, name: 'Moussa Niakhaté' },
          { num:  5, name: 'Abdoulaye Seck' },
          { num:  6, name: 'Ismail Jakobs' },
          { num:  7, name: 'El Hadji Malick Diouf' },
          { num:  8, name: 'Kalidou Koulibaly' },
          { num:  9, name: 'Idrissa Gana Gueye' },
          { num: 10, name: 'Pape Matar Sarr' },
          { num: 11, name: 'Pape Gueye' },
          { num: 12, name: 'Habib Diarra' },
          { num: 14, name: 'Lamine Camara' },
          { num: 15, name: 'Sadio Mané' },
          { num: 16, name: 'Ismaïla Sarr' },
          { num: 17, name: 'Soliave Dia' },
          { num: 18, name: 'Iliman Ndiaye' },
          { num: 19, name: 'Nicolas Jackson' },
          { num: 20, name: 'Nsepn Diatta' },
        ]
      },
      {
        id: 'IRQ', name: 'Iraque', flag: '🇮🇶',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Jalal Hassan' },
          { num:  3, name: 'Rebin Sulaka' },
          { num:  4, name: 'Hussein Ali' },
          { num:  5, name: 'Akam Hashem' },
          { num:  6, name: 'Mertchas Doski' },
          { num:  7, name: 'Zao Tahseen' },
          { num:  8, name: 'Manaf Younis' },
          { num:  9, name: 'Zidane Iqbal' },
          { num: 10, name: 'Amir Al-Ammari' },
          { num: 11, name: 'Ibrahim Bayesh' },
          { num: 12, name: 'Ali Jasim' },
          { num: 14, name: 'Youssef Amyn' },
          { num: 15, name: 'Amar Sher' },
          { num: 16, name: 'Mano Farj' },
          { num: 17, name: 'Osama Rashid' },
          { num: 18, name: 'Ali Al-Hamadi' },
          { num: 19, name: 'Ameen Hussein' },
          { num: 20, name: 'Mohamed Ali' },
        ]
      },
      {
        id: 'NOR', name: 'Noruega', flag: '🇳🇴',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Ørjan Nyland' },
          { num:  3, name: 'Jann Ryerson' },
          { num:  4, name: 'Leo Østigård' },
          { num:  5, name: 'Kristoffer Vassbakk Ajer' },
          { num:  6, name: 'Marcus Holmgren Pedersen' },
          { num:  7, name: 'Dag Mørk Wolfe' },
          { num:  8, name: 'Torbjørn Heggem' },
          { num:  9, name: 'Morten Thorsby' },
          { num: 10, name: 'Martin Ødegaard' },
          { num: 11, name: 'Sander Berge' },
          { num: 12, name: 'Andreas Schjelderup' },
          { num: 14, name: 'Patrick Berg' },
          { num: 15, name: 'Erling Haaland' },
          { num: 16, name: 'Alexander Sørloth' },
          { num: 17, name: 'Aron Dønnum' },
          { num: 18, name: 'Jørgen Strand Larsen' },
          { num: 19, name: 'Antonio Nusa' },
          { num: 20, name: 'Oscar Bobb' },
        ]
      },
    ]
  },

  /* ── GRUPO J ──────────────────────────────────────────────── */
  {
    group: 'J', label: 'Grupo J',
    teams: [
      {
        id: 'ARG', name: 'Argentina', flag: '🇦🇷',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Emiliano Martínez' },
          { num:  3, name: 'Nahuel Molina' },
          { num:  4, name: 'Cristian Romero' },
          { num:  5, name: 'Nicolás Otamendi' },
          { num:  6, name: 'Nicolás Tagliafico' },
          { num:  7, name: 'Leonardo Balerdi' },
          { num:  8, name: 'Enzo Fernández' },
          { num:  9, name: 'Alexis Mac Allister' },
          { num: 10, name: 'Rodrigo De Paul' },
          { num: 11, name: 'Exequiel Palacios' },
          { num: 12, name: 'Leandro Paredes' },
          { num: 14, name: 'Nico Paz' },
          { num: 15, name: 'Franco Mastantuono' },
          { num: 16, name: 'Nicolás González' },
          { num: 17, name: 'Lionel Messi' },
          { num: 18, name: 'Lautaro Martínez' },
          { num: 19, name: 'Julián Álvarez' },
          { num: 20, name: 'Giovani Simeone' },
        ]
      },
      {
        id: 'ALG', name: 'Argélia', flag: '🇩🇿',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Alexis Guendouze' },
          { num:  3, name: 'Ramy Bensebaïni' },
          { num:  4, name: 'Youcef Atal' },
          { num:  5, name: 'Rayan Aït-Nouri' },
          { num:  6, name: 'Mohamed Amine Tougai' },
          { num:  7, name: 'Aïssa Mandi' },
          { num:  8, name: 'Ismaël Bennacer' },
          { num:  9, name: 'Houssem Aouar' },
          { num: 10, name: 'Hicham Boudaoui' },
          { num: 11, name: 'Hamiz Zerouki' },
          { num: 12, name: 'Nabil Bentaleb' },
          { num: 14, name: 'Fares Chaïbi' },
          { num: 15, name: 'Riyad Mahrez' },
          { num: 16, name: 'Saïd Benrahma' },
          { num: 17, name: 'Anis Hadj Moussa' },
          { num: 18, name: 'Amine Gouiri' },
          { num: 19, name: 'Baghdad Bounedjah' },
          { num: 20, name: 'Mohammed Amoura' },
        ]
      },
      {
        id: 'AUT', name: 'Áustria', flag: '🇦🇹',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Alexander Schlager' },
          { num:  3, name: 'Patrick Pentz' },
          { num:  4, name: 'David Alaba' },
          { num:  5, name: 'Kevin Danso' },
          { num:  6, name: 'Philipp Lienhart' },
          { num:  7, name: 'Stefan Posch' },
          { num:  8, name: 'Philipp Mwene' },
          { num:  9, name: 'Alexander Prass' },
          { num: 10, name: 'Xaver Schlager' },
          { num: 11, name: 'Marcel Sabitzer' },
          { num: 12, name: 'Konrad Laimer' },
          { num: 14, name: 'Florian Grillitsch' },
          { num: 15, name: 'Nicolas Seiwald' },
          { num: 16, name: 'Romano Schmid' },
          { num: 17, name: 'Patrick Wimmer' },
          { num: 18, name: 'Christoph Baumgartner' },
          { num: 19, name: 'Michael Gregoritsch' },
          { num: 20, name: 'Marko Arnautovic' },
        ]
      },
      {
        id: 'JOR', name: 'Jordânia', flag: '🇯🇴',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Wazeef Abulayla' },
          { num:  3, name: 'Ihsan Haggag' },
          { num:  4, name: 'Mohammad Abu Hashish' },
          { num:  5, name: 'Rozan Al-Arab' },
          { num:  6, name: 'Abdullah Nasib' },
          { num:  7, name: 'Salem Obaid' },
          { num:  8, name: 'Mohammad Abualnaadi' },
          { num:  9, name: 'Ibrahima Saadeh' },
          { num: 10, name: 'Nizar Al-Rashdan' },
          { num: 11, name: 'Noor Al-Rawabdeh' },
          { num: 12, name: 'Mohammad Abu Taha' },
          { num: 14, name: 'Amer Jawous' },
          { num: 15, name: 'Mousa Al-Tamari' },
          { num: 16, name: 'Willan Al-Nawwat' },
          { num: 17, name: 'Mahmood Al-Mardi' },
          { num: 18, name: 'Ali Olwan' },
          { num: 19, name: 'Mohammad Abu Zraiq' },
          { num: 20, name: 'Ibrahim Sabraah' },
        ]
      },
    ]
  },

  /* ── GRUPO K ──────────────────────────────────────────────── */
  {
    group: 'K', label: 'Grupo K',
    teams: [
      {
        id: 'POR', name: 'Portugal', flag: '🇵🇹',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Diogo Costa' },
          { num:  3, name: 'José Sá' },
          { num:  4, name: 'Rúben Dias' },
          { num:  5, name: 'João Cancelo' },
          { num:  6, name: 'Diogo Dalot' },
          { num:  7, name: 'Nuno Mendes' },
          { num:  8, name: 'Gonçalo Inácio' },
          { num:  9, name: 'Bernardo Silva' },
          { num: 10, name: 'Bruno Fernandes' },
          { num: 11, name: 'Rúben Neves' },
          { num: 12, name: 'Vitinha' },
          { num: 14, name: 'João Neves' },
          { num: 15, name: 'Cristiano Ronaldo' },
          { num: 16, name: 'Francisco Trincão' },
          { num: 17, name: 'João Félix' },
          { num: 18, name: 'Gonçalo Ramos' },
          { num: 19, name: 'Pedro Neto' },
          { num: 20, name: 'Rafael Leão' },
        ]
      },
      {
        id: 'COD', name: 'Congo DR', flag: '🇨🇩',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Lionel Mpasi' },
          { num:  3, name: 'Aaron Wan-Bissaka' },
          { num:  4, name: 'Axel Tuanzebe' },
          { num:  5, name: 'Arthur Masuaku' },
          { num:  6, name: 'Chancel Mbemba' },
          { num:  7, name: 'Jros Kavembe' },
          { num:  8, name: 'Charles Pickel' },
          { num:  9, name: 'Njeavel Mukau' },
          { num: 10, name: 'Edo Kavembe' },
          { num: 11, name: 'Samuel Moutoussamy' },
          { num: 12, name: 'Noah Sadiki' },
          { num: 14, name: 'Théo Bongonda' },
          { num: 15, name: 'Meshack Elia' },
          { num: 16, name: 'Yoane Wissa' },
          { num: 17, name: 'Brian Cipenga' },
          { num: 18, name: 'Fiston Mayele' },
          { num: 19, name: 'Cédric Bakambu' },
          { num: 20, name: 'Nathanaël Mbuku' },
        ]
      },
      {
        id: 'UZB', name: 'Uzbequistão', flag: '🇺🇿',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Utkirjon Yusupov' },
          { num:  3, name: 'Farrukh Sayev' },
          { num:  4, name: 'Sherzod Nasrullaev' },
          { num:  5, name: 'Umar Eshmurodov' },
          { num:  6, name: 'Husnodin Aliulov' },
          { num:  7, name: 'Rustam Ashurmatov' },
          { num:  8, name: 'Khojiakbar Alijonov' },
          { num:  9, name: 'Abdukodir Khusanov' },
          { num: 10, name: 'Odiljon Hamrobekov' },
          { num: 11, name: 'Otabek Shukurov' },
          { num: 12, name: 'Jamshed Iskanderov' },
          { num: 14, name: 'Azizbek Turgunboev' },
          { num: 15, name: 'Khujamat Erkinov' },
          { num: 16, name: 'Eldor Shomurodov' },
          { num: 17, name: 'Oston Urunov' },
          { num: 18, name: 'Jaloliddin Masharipov' },
          { num: 19, name: 'Igor Sergeev' },
          { num: 20, name: 'Abrorberdi Fayzullaev' },
        ]
      },
      {
        id: 'COL', name: 'Colômbia', flag: '🇨🇴',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Camilo Vargas' },
          { num:  3, name: 'David Ospina' },
          { num:  4, name: 'Davinson Sánchez' },
          { num:  5, name: 'Yerry Mina' },
          { num:  6, name: 'Daniel Muñoz' },
          { num:  7, name: 'Johan Mojica' },
          { num:  8, name: 'Jhon Lucumí' },
          { num:  9, name: 'Santiago Arias' },
          { num: 10, name: 'Jefferson Lerma' },
          { num: 11, name: 'Kevin Castaño' },
          { num: 12, name: 'Richard Ríos' },
          { num: 14, name: 'James Rodríguez' },
          { num: 15, name: 'Juan Fernando Quintero' },
          { num: 16, name: 'Jorge Carrascal' },
          { num: 17, name: 'Juan Arias' },
          { num: 18, name: 'Jhon Córdoba' },
          { num: 19, name: 'Luis Suárez' },
          { num: 20, name: 'Luis Díaz' },
        ]
      },
    ]
  },

  /* ── GRUPO L ──────────────────────────────────────────────── */
  {
    group: 'L', label: 'Grupo L',
    teams: [
      {
        id: 'ENG', name: 'Inglaterra', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Jordan Pickford' },
          { num:  3, name: 'John Stones' },
          { num:  4, name: 'Marc Guéhi' },
          { num:  5, name: 'Ezri Konsa' },
          { num:  6, name: 'Trent Alexander-Arnold' },
          { num:  7, name: 'Reece James' },
          { num:  8, name: 'Dan Burn' },
          { num:  9, name: 'Jordan Henderson' },
          { num: 10, name: 'Declan Rice' },
          { num: 11, name: 'Jude Bellingham' },
          { num: 12, name: 'Cole Palmer' },
          { num: 14, name: 'Morgan Rogers' },
          { num: 15, name: 'Anthony Gordon' },
          { num: 16, name: 'Phil Foden' },
          { num: 17, name: 'Bukayo Saka' },
          { num: 18, name: 'Harry Kane' },
          { num: 19, name: 'Marcus Rashford' },
          { num: 20, name: 'Ollie Watkins' },
        ]
      },
      {
        id: 'CRO', name: 'Croácia', flag: '🇭🇷',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Dominik Livaković' },
          { num:  3, name: 'Josip Juranović' },
          { num:  4, name: 'Joško Gvardiol' },
          { num:  5, name: 'Duje Ćaleta-Car' },
          { num:  6, name: 'Dejan Lovren' },
          { num:  7, name: 'Borna Sosa' },
          { num:  8, name: 'Marcelo Brozović' },
          { num:  9, name: 'Mateo Kovačić' },
          { num: 10, name: 'Luka Modrić' },
          { num: 11, name: 'Ivan Perišić' },
          { num: 12, name: 'Mario Pašalić' },
          { num: 14, name: 'Nikola Vlašić' },
          { num: 15, name: 'Lovro Majer' },
          { num: 16, name: 'Ante Budimir' },
          { num: 17, name: 'Bruno Petković' },
          { num: 18, name: 'Andrej Kramarić' },
          { num: 19, name: 'Marko Livaja' },
          { num: 20, name: 'Ivan Zucco' },
        ]
      },
      {
        id: 'GHA', name: 'Gana', flag: '🇬🇭',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Lawrence Ati-Zigi' },
          { num:  3, name: 'Tariq Lamptey' },
          { num:  4, name: 'Mohammed Salisu' },
          { num:  5, name: 'Alidu Seidu' },
          { num:  6, name: 'Alexander Djiku' },
          { num:  7, name: 'Gideon Mensah' },
          { num:  8, name: 'Caleb Wirenk-Acheampong' },
          { num:  9, name: 'Abdul Salis Fatawu' },
          { num: 10, name: 'Thomas Partey' },
          { num: 11, name: 'Salis Abdul Samed' },
          { num: 12, name: 'Kamaledeen Sulemana' },
          { num: 14, name: 'Mohammed Kudus' },
          { num: 15, name: 'Iñaki Williams' },
          { num: 16, name: 'Jordan Ayew' },
          { num: 17, name: 'André Ayew' },
          { num: 18, name: 'Joseph Paintsil' },
          { num: 19, name: 'Osman Bukari' },
          { num: 20, name: 'Antoine Semenyo' },
        ]
      },
      {
        id: 'PAN', name: 'Panamá', flag: '🇵🇦',
        players: [
          { num:  1, name: 'Escudo' },
          { num:  2, name: 'Orlando Mosquera' },
          { num:  3, name: 'Luís Mejía' },
          { num:  4, name: 'Fidel Escobar' },
          { num:  5, name: 'Andrés Andrade' },
          { num:  6, name: 'Michaelangelo Murillo' },
          { num:  7, name: 'Eric Davis' },
          { num:  8, name: 'José Córdoba' },
          { num:  9, name: 'César Blackman' },
          { num: 10, name: 'Cristian Martínez' },
          { num: 11, name: 'Aníbal Godoy' },
          { num: 12, name: 'Adalberto Carrasquilla' },
          { num: 14, name: 'Edgar Bárcenas' },
          { num: 15, name: 'Carlos Harvey' },
          { num: 16, name: 'Ismael Díaz' },
          { num: 17, name: 'José Fajardo' },
          { num: 18, name: 'Cecilio Waterman' },
          { num: 19, name: 'José Luís Rodríguez' },
          { num: 20, name: 'Alberto Quintero' },
        ]
      },
    ]
  },

  /* ── COCA-COLA COLLECTION (CC) ───────────────────────────── */
  {
    group: 'CC',
    label: 'Coca-Cola Collection',
    special: true,
    teams: [
      {
        id: 'CC', name: 'Coca-Cola Collection', flag: '🥤',
        players: [
          { num:  1, name: 'CC 1'  },
          { num:  2, name: 'CC 2'  },
          { num:  3, name: 'CC 3'  },
          { num:  4, name: 'CC 4'  },
          { num:  5, name: 'CC 5'  },
          { num:  6, name: 'CC 6'  },
          { num:  7, name: 'CC 7'  },
          { num:  8, name: 'CC 8'  },
          { num:  9, name: 'CC 9'  },
          { num: 10, name: 'CC 10' },
          { num: 11, name: 'CC 11' },
          { num: 12, name: 'CC 12' },
          { num: 13, name: 'CC 13' },
          { num: 14, name: 'CC 14' },
        ]
      }
    ]
  },
];
